### ISSUE TITLE
Project ideas

### ISSUE THREAD

**Issue by AdamRJensen** [PVSC-Python-Tutorials/PVPMC_2023#3]
@kandersolar and I have come up with the following project ideas for the pvlib workshop at PVPMC 2023.

We'd appreciate some feedback and additional project suggestions 😄  @shirubana @mikofski @cwhanse @mtheristis

**Edit: the project list have been updated based on the feedback below**

*Easy*:
- [x] Compare the annual irradiation for Salt Lake City using data from NSRDB PSM3 and ERA5 from PVGIS
- [ ] ~~Calculate irradiance for a south-facing surface with a 40° tilt~~
- [ ] ~~Determine the time of highest solar elevation today in Salt Lake City~~

*Medium*:
- [x] Calculate the optimal tilt angle of a fixed-tilt system
- [x] Calculate the power output of a roof-top using the PVWatts functionality pvlib
- [x] Calculate plane-of-array irradiance using several of the available transposition models, and compare the variation among models
- [x] Retrieve long-term irradiance data from PSM3 and generate a CDF and determine the mean, median, and 95th percentiles

*Advanced*:
- [ ] ~~Implement a smart tracking algorithm and calculate performance gain compared to standard tracking~~
- [x] Determine the bifacial performance gain of a fixed-tilt system
- [x] Contribute to pvlib by adding the Orgill and Hollands diffuse fraction estimation algorithm
- [ ] Retrieve long-term rain data, generate a CDF of dust soiling losses for a ground-based fixed tilt system in SLC, and determine the mean, median, and 95th percentiles

**Comment by mikofski** [comment]
Looks good. Thanks!

>easy: Compare the annual irradiation for Salt Lake City using data from NSRDB PSM3 and PVGIS

TBH: I think PVGIS will also return PSM3 for SLC, so they might be identical, but depends if it is TMY, how which years used to generate, and if horizon is included or not. Both PVGIS and PSM3 have the ability to also return indie years from long term datasets as well. So I think it would be interesting if we can make legacy tmy2/3 files for SLC available and have them compare them to other TMY files. Could we get SolarAnywhere to contribute a SLC tmy for the tutorial?

medium: retrieve long term data from PSM3 and generate a CDF and determine the mean, median, and 95th percentiles

hard: retrieve long term rain data, generate a CDF of dust soiling losses for a ground based fixed tilt system in SLC, and determine the mean, media, and 95th percentiles

very hard: ditto for snow, but compare Townsend to Marion

---

I think it's important to stress that while there may be conventions and Pythonic idioms, the outputs of the analysis are subjective, maybe there are no right answers, and all ideas are good ideas. This should be a safe space without judgement. I'm really curious to hear what folks come up with!

**Comment by AdamRJensen** [comment]
> TBH: I think PVGIS will also return PSM3 for SLC, so they might be identical, but depends if it is TMY, how which years used to generate, and if horizon is included or not. Both PVGIS and PSM3 have the ability to also return indie years from long term datasets as well. So I think it would be interesting if we can make legacy tmy2/3 files for SLC available and have them compare them to other TMY files. Could we get SolarAnywhere to contribute a SLC tmy for the tutorial?

@mikofski Good point. Luckily pvgis can also return era5 worldwide. I also contacted CPR and have received a TMY file from SolarAnywhere. I'll upload a couple of TMYs for SLC in the next couple of days.

Also, Kevin and I will send out an email to the PVPMC participants on Monday.

**Comment by AdamRJensen** [comment]
Closing this issue since we've decided on the project ideas. The project ideas have been created as GitHub Discussions - feel free to edit or clarify.

Thanks all for contributing! 😄
